Meteor.subscribe('userWallet', Meteor.userId());
Meteor.subscribe("userData");
Meteor.subscribe('corporates');
Meteor.subscribe("jobCount");
Meteor.subscribe('providers');
Meteor.subscribe('buyers');
Meteor.subscribe("developerCount");
Meteor.subscribe("userList");
Meteor.subscribe('categories');
Meteor.subscribe('subcategories');
Meteor.subscribe('skills');
Meteor.subscribe('adminJobCount');
Meteor.subscribe('allCompletedJobs');
Meteor.subscribe('usersCount');